[package]
name = "archivindex-warc-cli"
version.workspace = true
description = "Command-line tools for working with WARC files"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
archivindex-warc.workspace = true
archivindex-warc-ops = { path = "../ops" }
clap.workspace = true
csv.workspace = true
d2-little = "0.7.1-1"
flate2.workspace = true
fluent-uri.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
simplelog.workspace = true
tempfile.workspace = true
