[package]
name = "archivindex-warc-cli"
version.workspace = true
description = "Command-line tools for working with WARC files"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
archivindex-warc.workspace = true
archivindex-warc-ops = { path = "../ops" }
clap = { version = "4.5", features = ["derive"] }
csv = "1"
d2-little = "0.7.1-1"
flate2.workspace = true
fluent-uri.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
simplelog = "0.12"
tempfile.workspace = true
