[package]
name = "archivindex-warc-linter"
version.workspace = true
description = "Lint WARC files against standard requirements and additional conventions"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
archivindex-warc.workspace = true
fluent-uri.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
flate2.workspace = true
serde_json.workspace = true
