[package]
name = "archivindex-warc-ops"
version.workspace = true
description = "Higher-level operations for WARC files"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
archivindex-warc.workspace = true
flate2.workspace = true
fluent-uri.workspace = true
log.workspace = true
md-5.workspace = true
sha1.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
